app/routes/super_routes.py
from flask import flash, jsonify, render_template, request, redirect, url_for, Blueprint

from app.models import Asignatura
from app.repositories.record_repository import RecordRepository
from app.repositories.time_repository import TimeRepository
from app.services.academic_service import AcademicService
from app.services.settings_service import UserSettings
from app.services.time_service import UserTime
from app.services.user_service import UserService
from app.utils.ms_to_hms import ms_to_hms
from app.utils.debugging_utils import printn
from app.utils.helpers import relation_required, supervisor_required, listar_asignaturas, listar_registro_notas, id_from_json, id_from_kwargs
from app.services.notifications_service import Notification, NotificationRepository
from app.services.grade_incentive_service import GradeIncentiveRepository, GradeIncentive, get_currency_data

from .. import db


super_bp = Blueprint('super', __name__)

@super_bp.route('/student_records/<id>')
@supervisor_required
@relation_required(id_from_kwargs)
def student_records(id):
    name = UserService.get_username_by_id(id)
    activity_obj = RecordRepository.get_records_list(id, 5)
    use_obj = TimeRepository.get_use_obj(id, 10)

    return render_template("s_records.html", estudios=activity_obj, usos=use_obj, name=name)

@super_bp.route('/grade_incentive/<id>')
@supervisor_required
@relation_required(id_from_kwargs)
def grade_incentive(id):
    asignaturas = listar_asignaturas(id)
    registro_notas = listar_registro_notas(id)

    user_settings = UserSettings(id)
    name = user_settings.name

    repo = GradeIncentiveRepository(db.session)
    grade_incentive = GradeIncentive(id, repo)
    best_grades = grade_incentive.filter_grades()

    return render_template('s_grade_incentive.html', asignaturas=asignaturas, registro_notas=registro_notas, best_grades=best_grades, name=name, user_id=id)

@super_bp.route("/grade_incentive/warning/<int:id>")
@supervisor_required
@relation_required(id_from_kwargs)
def grade_incentive_warning(id):
    flash(f"You must set at least 1 incentive in <a href='/settings/{id}'>Settings</a>", 'warning')
    return redirect(url_for('core.home'))

@super_bp.route('/grade_incentive/<id>', methods=['POST'])
@supervisor_required
@relation_required(id_from_kwargs)
def add_grade_incentive(id):
    data = request.get_json()

    asignatura_id = data.get('asignatura')
    tema = data.get('tema')
    nota = data.get('nota')
    fecha = data.get('fecha')

    AcademicService.add_grade(id, asignatura_id, tema, nota, fecha)
    asignatura_nombre = Asignatura.query.get(asignatura_id).nombre
    amount, currency, symbol = get_currency_data(id, nota)
    repo = NotificationRepository(db.session)
    notification = Notification(id, repo)
    notification.notify_grade(nota, asignatura_nombre, 'add', amount, currency, symbol)

    flash_msg = f"A new grade has been submited. Subject: <b>{asignatura_nombre}</b>, grade: <b>{nota}</b>"
    return jsonify({"flash": {"message": flash_msg, "category": "success"}})

    
@super_bp.route("/payment", methods=["PUT"])
@supervisor_required
def mark_paid():
    data = request.get_json()
    record_id = data.get('grade_to_pay')
    student_id = data.get('estudiante_id')
    
    grade, subject = AcademicService.get_grade_and_subject(record_id)
    amount, currency, symbol = get_currency_data(student_id, grade)

    AcademicService.set_grade_as_paid(record_id)

    repo = NotificationRepository(db.session)
    notification = Notification(student_id, repo)
    notification.notify_grade(grade, subject, 'pay', amount, currency, symbol)
    
    flash("The payment has been recorded successfully", "success")
    return redirect(url_for("super.grade_incentive", id=student_id))

@super_bp.route("/trophy/<int:id>", methods=["POST"])
@supervisor_required
@relation_required(id_from_kwargs)
def set_trophy(id):
    reward = request.form.get("reward", "").strip()
    user_settings = UserSettings(id)

    if not reward:
        flash("Isn't possible to submit empty data as a Trophy.", "warning")
        return redirect(url_for("core.settings", id=id))

    user_settings.set_trophy(reward)
    flash(f"A new trophy has been set up: <b>{reward}</b>", "success")
    return redirect(url_for("core.settings", id=id))

@super_bp.route("/extra_time/<int:id>/<int:extra_time>", methods=["PUT"])
@supervisor_required
@relation_required(id_from_kwargs)
def set_extra_time(id, extra_time):
    user_settings = UserSettings(id)
    user_settings.set_extra_time(extra_time)
    return jsonify({"status": "success"}), 200

@super_bp.route("/study_fun_ratio/<int:id>/<ratio>", methods=["PUT"])
@supervisor_required
@relation_required(id_from_kwargs)
def set_study_fun_ratio(id, ratio):
    user_settings = UserSettings(id)
    user_settings.set_study_fun_ratio(ratio)
    return jsonify({"status": "success"}), 200

@super_bp.route("/s_time/<int:id>")
@supervisor_required
@relation_required(id_from_kwargs)
def time_information(id):
    user_time = UserTime(id)
    current_time = user_time.get_time()
    settings = UserSettings(id)
    name = settings.name
    return render_template("s_time.html", current_time=current_time, user_id=id, name=name)

@super_bp.route("/s_time", methods=["PUT"])
@supervisor_required
@relation_required(id_from_json)
def manage_time():
    data = request.get_json()
    time = data.get("time")
    id = data.get("estudiante_id")
    action = data.get("action")
    user_time = UserTime(id)
    current_time = user_time.get_time()
    previous_time = ms_to_hms(current_time)
    new_time = user_time.manage_time(action, time)
    
    flash(f"Time updated, previous time: <b>{previous_time}</b>", "success")
    return jsonify({"new_time": new_time, "previous_time": current_time}), 200

@super_bp.route("/s_time/reset", methods=["PUT"])
@supervisor_required
@relation_required(id_from_json)
def reset_time():
    data = request.get_json()
    id = data.get("estudiante_id")
    user_time = UserTime(id)
    current_time = user_time.get_time()
    previous_time = ms_to_hms(current_time)
    reset = user_time.reset_time()

    flash(f"The time has been reset. Previous time <b>{previous_time}</b>", "success")
    return jsonify({"new_time": reset, "previous_time": current_time}), 201

app/templates/add_time.html
{% extends 'base.html' %}

{% block title %}Add Time{% endblock %}

{% block content %}

<div class="custom-bg-1 custom-text-2 p-4 rounded-4 mb-5">
  <div class="d-flex justify-content-center custom-fs-1">
    <div class="custom-text-2">
      <span id="hour">00</span>
      <span id="colon">:</span>
      <span id="minute">00</span>
      <span id="colon">:</span>
      <span id="second">00</span>
    </div>
  </div>
  <div class="d-flex justify-content-center">
    <button id="start" class="btn custom-btn mb-5" onclick="logClick('Start studying')">Start studying</button>
  </div>
  
  <div class="align-items-start">
      <div class="d-flex mb-3 justify-content-center gap-3">
        <select class="select-dark" name="asignaturas" id="asignaturas" required>
          <option value="">Select a subject...</option>
          {% for asignatura in asignaturas %}
            <option value="{{ asignatura.id }}">{{ asignatura.nombre | capitalize }}</option>
          {% endfor %}
        </select>
        <a href="/subject" class="btn custom-btn-3">Subject management</a>
      </div>
      <div>
        <div class="mb-1">Summary:</div>
        <textarea class="form-control mb-3 custom-textarea" name="summary" id="summary" placeholder="Summary of what I studied in this session" required></textarea>
      </div>
  </div>
    <div class="d-flex justify-content-center gap-4">
      
        <button id="stop" class="btn custom-btn-2 btn-loading" onclick="logClick('Submit session')" disabled>
          <span class="btn-text">Submit session</span>
          <span class="btn-loader"></span>
        </button>
      
      
        <button id="cancel" class="btn custom-btn-3 btn-loading" onclick="logClick('Cancel')">
          <span class="btn-text">Cancel</span>
          <span class="btn-loader"></span>
        </button>
      
    </div>
  </form>
</div>
<br><br>

<script src="{{ url_for('static', filename='js/timerAdd.js') }}"></script>

{% endblock %}

app/templates/flash_messages.html
<div id="flash-messages" class="hidden">
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        {% set bootstrap_class = {
            "error": "danger",
            "success": "success",
            "warning": "warning",
            "info": "info"
        }[category] %}
        <div class="alert alert-{{ bootstrap_class }} mt-2" role="alert">
          {{ message | safe }}
        </div>
      {% endfor %}
    {% endif %}
  {% endwith %}
</div>

app/templates/incentivo_notas.html
<div class="my-4"></div>

<div class="d-flex flex-column align-items-start justify-content-around flex-sm-row align-items-sm-start">
    <div>
        <h4>Incentives</h4>
        
        {% if incentivos != [] %}
        <ul class="no-indent">
        {% for incentivo in incentivos %}
            <li>
                {{ incentivo | safe }}
            </li>
        {% endfor %}
        </ul>
        {% else %}
            There is no incentives yet.
        {% endif %}
    </div>
    
    <div>
        <h4>Restrictions</h4>
        
        {% if restricciones != [] %}
        <ul class="no-indent">
        {% for restriccion in restricciones %}
            <li>
                {{ restriccion }}
            </li>
        {% endfor %}
        </ul>
        {% else %}
            There is no restrictions yet.
        {% endif %}
    </div>
</div>

app/templates/notificaciones.html
{% extends "base.html" %}
{% block content %}

<div class="custom-bg-1 custom-text-2 p-4 rounded-4 mb-5">
  <div class="d-flex flex-column align-items-center">
    <h3>Notifications</h3>
    <div class="list-group w-100 mt-3">
      
      {% if notificaciones %}
        {% for notificacion in notificaciones %}
        <div class="list-group-item">
          {{ notificacion.notificacion | safe }}
        </div>  
        {% endfor %}
      {% else %}
      <div align="center">There aren't notifications yet.</div>
      {% endif %}
    </div>
    
  </div>
</div>
<br>
<br>

<script>
  function responderSolicitud(id, respuesta)  {
    fetch('/request_response', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        sid: id,
        response: respuesta
      })
    })
    .then(res => {
      if (!res.ok) throw new Error('Error en la solicitud')
      return res.json()
    })
    .then(data => {
      const acciones = document.getElementById(`acciones-${id}`)
      if (acciones) acciones.remove()
      window.location.reload()
    })
    .catch(error => {
      console.error(error)
      alert('Hubo un problema al procesar la solicitud')
    })
  }
</script>
{% endblock %}

app/templates/perfil.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}

{% block content %}

<div class="custom-bg-1 custom-text-2 p-4 rounded-4 mb-5">
  <p class="mb-4 text-center">Welcome, {{ nombre | capitalize }}!</p>
{% if not estudios %}
    <p class="text-center">Record your first study time <a href="/add_time" style="color:#fb7833">here</a>.</p>
</div>
<br><br>
{% else %}
  {% include 'progreso.html'%}
</div>
<div class="custom-bg-1 custom-text-2 p-4 rounded-4 mb-5">
    <h2 class="mb-4 text-center">Percentages of study</h2>
    {% include 'porcentajes.html'%}
</div>
  {% if incentivos != [] %}
    <div class="custom-bg-1 custom-text-2 p-4 rounded-4 mb-5">
    <h2 class="mb-4 text-center">Grade Incentive</h2>
    {% include 'incentivo_notas.html'%}
    </div>
  {% endif %}
<br><br>
{% endif %}
<script>
  if (window.location.search.includes("reload=true")) {
    
    const url = new URL(window.location.href)
    url.searchParams.delete("reload")
    window.history.replaceState({}, document.title, url.pathname)
    window.location.reload()
  }
</script>
{% endblock %}

app/templates/porcentajes.html
{% for key, value in porcentajes_asignaturas.items() %}
<div class="mb-3">
    {{ key | capitalize }}: {{ value }}%
    <div class="progress-container">
    <div class="progress-bar" style="width: {{ value }}%;"></div>
    </div>
</div>
{% endfor %}

app/templates/progreso.html
<div class="d-flex flex-column flex-md-row justify-content-around align-items-md-end gap-5">
    <!-- Trofeos -->
    <div class="d-flex flex-column align-items-center">
        <img src="{{ url_for('static', filename='img/trofeo.png') }}" alt="trofeo" height="64">
        <div class="custom-text-3 fs-3 mt-2">
            <strong>Trophies: {{ trofeos }}</strong>
        </div>
    </div>

    <!-- Estrellas + Nivel -->
    <div class="d-flex flex-column align-items-center">
        <div class="d-flex justify-content-center mb-2 gap-2 flex-wrap">
            {% for estrella in estrellas %}
                {% if estrella %}
                    <img src="{{ url_for('static', filename='img/star.png') }}" alt="estrella" height="32">
                {% else %}
                    <img src="{{ url_for('static', filename='img/template_star.png') }}" alt="estrella" height="32">
                {% endif %}
            {% endfor %}
        </div>
        <span class="custom-text-3 fs-3"><strong>Level: {{ nivel }}</strong></span>
    </div>
</div>

app/templates/record_list.html
<div class="table-responsive">
  <table class="table table-dark table-bordered text-center custom-text-2 table-striped !important">
    <thead>
      <tr class="custom-text-1">
        <th>Date</th>
        <th>Time</th>
        <th>Details</th>
      </tr>
    </thead>
    <tbody>
      {% for estudio in estudios %}
      <tr class="align-middle">
        <td>{{ estudio.fecha_inicio.strftime('%d-%m-%Y') }}</td>
        <td>{{ (estudio.fecha_fin - estudio.fecha_inicio) }}</td>
        <td>
          <a class="text-decoration-none cursor-pointer" role="button" onclick="toggleDetails( {{ loop.index }} )">
            <iconify-icon id="icon-{{ loop.index }}" icon="material-symbols:zoom-in-rounded" style="color: #fbc93e" width="32"
              height="32"></iconify-icon>
          </a>
        </td>
      </tr>
      <tr id="resumen-row-{{ loop.index }}" style="display: none;">
        <td colspan="4" class="p-3">
          <div class="d-flex justify-content-between mb-2">
            <div><strong>Start:</strong> {{ estudio.fecha_inicio.strftime('%H:%M:%S') }}</div>
            <div><strong>End:</strong> {{ estudio.fecha_fin.strftime('%H:%M:%S') }}</div>
          </div>
          <div class="text-start mb-2">
            <strong>Subject:</strong> {{ estudio.asignatura.nombre | capitalize }}
          </div>
          <div class="d-flex justify-content-between">
            <strong>Summary:</strong>
            <a href="/edit_record/{{ estudio.id }}"><iconify-icon icon="mdi:comment-edit" width="24" height="24" style="color: {{ '#fbc93e' }}"></iconify-icon></a>
          </div>
          <div class="text-start">
            <p style="white-space: pre-line;">{{ estudio.resumen | markdown | safe }}</p>
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<script>
  function toggleDetails(index) {
    const resumenRow = document.getElementById(`resumen-row-${index}`)
    const icon = document.getElementById(`icon-${index}`)

    if (resumenRow.style.display === "none") {
      resumenRow.style.display = "table-row"
      resumenRow.classList.add("resumen-visible")
      icon.setAttribute("icon", "material-symbols:zoom-out-rounded")
      icon.setAttribute("style", "color: #fb7833")
    } else {
      resumenRow.style.display = "none"
      resumenRow.classList.remove("resumen-visible")
      icon.setAttribute("icon", "material-symbols:zoom-in-rounded")
      icon.setAttribute("style", "color: #fbc93e")

    }
  }
</script>

app/templates/s_settings.html
{% extends 'base_supervisor.html' %}

{% block title %}Settings{% endblock %}

{% block content %}

<div class="custom-bg-1 custom-text-2 p-4 rounded-4 mb-5">
  <div class="d-flex justify-content-between">
    <h5>Settings</h5>
    <p>{{ name }}</p>
  </div>
  
  <!-- ratio -->
  <div class="my-4">
    <p class="fs-2">Study-Fun Ratio</p>
    <p>Set the ratio between study time and fun time.</p> 
    <label for="study-fun-ratio">For every:</label>
    <select name="study-fun-ratio" id="study-fun-ratio" class="select-dark">
      <option value="0.5" {% if study_fun_ratio == 0.5 %}selected{% endif %}>2 hours of study, 1 hour of fun</option>
      <option value="0.571429" {% if study_fun_ratio == 0.571429 %}selected{% endif %}>1:45 hours of study, 1 hour of fun</option>
      <option value="0.666667" {% if study_fun_ratio == 0.666667 %}selected{% endif %}>1:30 hours of study, 1 hour of fun</option>
      <option value="0.8" {% if study_fun_ratio == 0.8 %}selected{% endif %}>1:15 hours of study, 1 hour of fun</option>
      <option value="1.0" {% if study_fun_ratio == 1.0 %}selected{% endif %}>1 hour of study, 1 hour of fun</option>
      <option value="1.25" {% if study_fun_ratio == 1.25 %}selected{% endif %}>1 hour of study, 1:15 hours of fun</option>
      <option value="1.5" {% if study_fun_ratio == 1.5 %}selected{% endif %}>1 hour of study, 1:30 hours of fun</option>
      <option value="1.75" {% if study_fun_ratio == 1.75 %}selected{% endif %}>1 hour of study, 1:45 hours of fun</option>
      <option value="2.0" {% if study_fun_ratio == 2.0 %}selected{% endif %}>1 hour of study, 2 hours of fun</option>
    </select>
  </div>
  
  <hr>
  
  <!-- level -->
  <div class="my-4">
    <p class="fs-2">Level</p>
    <p>After 10 study hours, the student reaches a new level and gets extra time set here.</p> 
    <label for="extra-time">Extra time:</label>
    <select name="extra-time" id="extra-time" class="select-dark">
      <option value="1800000" {% if extra_time == 1800000 %}selected{% endif %}>30 min</option>
      <option value="3600000" {% if extra_time == 3600000 %}selected{% endif %}>1 hour</option>
      <option value="7200000" {% if extra_time == 7200000 %}selected{% endif %}>2 hours</option>
    </select>
  </div>
  
  <hr>
  
  <!-- trophy-->
  <div class="my-4">
    <p class="fs-2">Trophy</p>
    <p>After 50 study hours, the student unlocks a new trophy and gets a custom reward. (i.e. $5.00 Steam Gift Card, 3 extra hours or $5.00 cash)</p>
    
    <div class="rounded custom-bg-grey py-2 px-2 d-flex align-content-center flex-column text-center mt-2 mb-4">
      <p class="mb-0">Current reward</p>
      <h5 class="mb-0">{{ trofeo | safe }}</h5>
    </div>
    
    <h5>Set new reward</h5>
    <form action="{{ url_for('super.set_trophy', id=estudiante_id) }}" method="POST" class="d-flex gap-2 align-items-center">
      <input id="reward_input" name="reward" type="text" class="form-control flex-shrink-1">
      <button type="submit" class="btn custom-btn-2 btn-loading">
        <span class="btn-text">Set</span>
        <span class="btn-loader"></span>
      </button>
    </form>
  </div>
  
  <hr>
  
  <!-- grade incentive-->
  <div class="my-4">
    <div class="d-flex justify-content-start align-items-center gap-2 mb-2">
      
      <label for="grade_incentive" class="fs-2">Grade incentive</label>
      
      <input type="checkbox" id="grade_incentive" name="grade_incentive" value="1" onclick="fetchIncentivoToggle({{ estudiante_id }})" {% if incentivo_notas %}checked{% endif %}>
      
      <div class="d-flex align-items-center tooltip-container">
        <iconify-icon id="infoIcon" class="cursor-pointer" icon="ic:twotone-info" width="20" height="20"></iconify-icon>
        <span class="tooltip-text">Monetary reward system for results applying personalized criteria</span>
      </div>
  
    </div>
    
    <div id="grade_incentive_section" style="{% if incentivo_notas %} display:block {% else %}display: none;{% endif %}">
      
        Country: 
        <select id="pais_select" class="flex-shrink-1 select-dark" onchange="handlePaisChange(this)">
          {% for pais in paises %}
            <option 
            value="{{ pais.id }}"
            {% if pais.id == pais_actual %}selected{% endif %}
            data-moneda="{{ pais.moneda }}"
            data-simbolo="{{ pais.simbolo }}"
            >
              {{ pais.pais }}
            </option>
          {% endfor %}
        </select>
      
      <div class="my-4"></div>
  
      <h5>Incentives</h5>
      <ul id="incentivos_ul">
          {% if incentivos %}
              {% for item in incentivos %}
              <li data-id="{{ item.id }}">
                  <div class="d-flex justify-content-start gap-2 align-content-center">
                      <div>{{ item.incentivo | safe }}</div>
                      <iconify-icon class="cursor-pointer" icon="ic:baseline-delete" width="20" height="20" onclick="handleDeleteIncentive({{ estudiante_id }}, {{ item.id }})"></iconify-icon>
                  </div>
              </li>
              {% endfor %}
          {% else %}
              <li id="no_incentives">There is no incentives yet.</li>
          {% endif %}
      </ul>
  
      <h5>Restrictions</h5>
      <ul id="restricciones_ul">
        {% if restricciones %}
          {% for item in restricciones %}
            <li data-id="{{ item.id }}">
              <div class="d-flex justify-content-start gap-2 align-content-center">
                <div>{{item.restriccion}}</div> 
                <iconify-icon class="cursor-pointer" icon="ic:baseline-delete" width="20" height="20" onclick="handleRemoveRestriction({{ estudiante_id }}, {{ item.id }})"></iconify-icon>
              </div>
            </li>
          {% endfor %}
        {% else %}
            <li id="no_restrictions">There is no restrictions yet.</li>
        {% endif %}
      </ul>
      
      <div class="my-4"></div>
      
      <h5>Add incentive</h5>
      <div class="d-flex flex-nowrap gap-2 align-items-center">
        
        <!-- monto -->
        <input type="text" id="monto" class="form-control flex-shrink-1" style="min-width:60px" placeholder="">
        
        <!-- texto -->
        <div class="text-nowrap"><span id="moneda_display"></span> for grades <b>&ge;</b></div>
        
        <!-- monto -->
        <select id="grade" class="select-dark"></select>
  
        <!-- enviar -->
        <button class="btn custom-btn-2 btn-loading" id="add_incentive_btn">
          <span class="btn-text">Add</span>
          <span class="btn-loader"></span>
      </div>
  
      <div class="my-4"></div>
      
      <h5>Add restriction</h5>
      <div class="d-flex gap-2 align-items-center">
        <input id="restriccion_input" type="text" class="form-control flex-shrink-1">
        <button class="btn custom-btn-2 btn-loading" id="addRestrictionBtn">
          <span class="btn-text">Add</span>
          <span class="btn-loader"></span>
        </button>
      </div>
    </div>
  </div>
</div>
<br><br>

<script src="{{ url_for('static', filename='js/settings_fetch.js') }}"></script>
<script src="{{ url_for('static', filename='js/settings_handling.js') }}"></script>


<script>

  
  const addIncentiveBtn = document.getElementById("add_incentive_btn")
  const addRestrictionBtn = document.getElementById("addRestrictionBtn")

  withLoader(addIncentiveBtn, () => handleAddIncentive(...incentiveVars()))
  withLoader(addRestrictionBtn, () => handleAddRestriction(...restrictionVars()))

  const extraTimeSelect = document.getElementById("extra-time")
  const timeRatioSelect = document.getElementById("study-fun-ratio")

  timeRatioSelect.addEventListener("change", () => {
    const ratio = timeRatioSelect.value
    const id = "{{ estudiante_id }}"
    fetchTimeFunRatio(id, ratio)
  })

  extraTimeSelect.addEventListener("change", () => {
    const extraTime = extraTimeSelect.value
    const id = "{{ estudiante_id }}"
    fetchSetExtraTime(id, extraTime)
  })

  
const selectPais = document.getElementById("pais_select")
const monedaDisplay = document.getElementById("moneda_display")
const simboloDisplay = document.getElementById("monto")
const selectSistema = document.getElementById("grade")

const sistemas = JSON.parse('{{ sistemas | tojson | safe }}')

function updateDisplay() {
  const selected = selectPais.options[selectPais.selectedIndex]
  monedaDisplay.textContent = selected.dataset.moneda
  simboloDisplay.placeholder = selected.dataset.simbolo
}

function updateSistema() {
  const paisId = selectPais.value
  const sistema = sistemas[paisId]

  selectSistema.innerHTML = ""
  if (sistema) {
    sistema.valores.forEach(val => {
      const opt = document.createElement("option")
      opt.value = val
      opt.textContent = val
      selectSistema.appendChild(opt)
    })
  }
}

function handlePaisChange(select) {
  updateDisplay()
  updateSistema()

  fetchCambiarPais("{{ estudiante_id }}", select.value)
}

handlePaisChange(selectPais)


document.getElementById("grade_incentive").addEventListener("change", function() {
  const div = document.getElementById("grade_incentive_section")
  div.style.display = this.checked ? "block" : "none"
})

const icon = document.getElementById("infoIcon")
const tooltip = icon.nextElementSibling

icon.addEventListener("click", () => {
  if (tooltip.style.visibility === "visible") {
    tooltip.style.visibility = "hidden"
    tooltip.style.opacity = "0"
  } else {
    tooltip.style.visibility = "visible"
    tooltip.style.opacity = "1"
  }
})

document.addEventListener("click", (e) => {
  if (!icon.parentElement.contains(e.target)) {
    tooltip.style.visibility = "hidden"
    tooltip.style.opacity = "0"
  }
})

function incentiveVars() {
  const estudianteId = "{{ estudiante_id }}"
  const monto = document.getElementById('monto').value
  const nota = document.getElementById('grade').value
  const simbolo = document.getElementById('monto').placeholder
  const moneda = document.getElementById('pais_select')
    .options[document.getElementById('pais_select').selectedIndex]
    .dataset.moneda

  return [ estudianteId, monto, nota, simbolo, moneda ]
}

function restrictionVars() {
  const estudianteId = "{{ estudiante_id }}"
  const restriccion = document.getElementById("restriccion_input").value

  return [estudianteId, restriccion]
}

</script>

{% endblock %}